### ISSUE TITLE
Is this example supposed to pass formal verification?

### ISSUE THREAD

**Issue by mgrojo** [Fabien-Chouteau/recordflux-example#3]
Hi Fabien,

Is this example supposed to pass formal verification? I tried `gnatprove -P example.gpr` and I get many verification failures, both in example.adb as in the source code generated by RecordFlux.

I'm using gnatprove 14.1.1 from Alire, in case the version used is important.

**Comment by Fabien-Chouteau** [comment]
Hi @mgrojo,

The output of RecordFlux is designed to be verified by the corresponding GNATprove release. 
So I am not too surprised you cannot prove with GNATprove FSF 14.

This repo is just a support for the blog post so I do not intend to update it.
